### ISSUE TITLE
FullHash + UTFGrid

### ISSUE THREAD

**Issue by VoyteckPL** [KoGor/leaflet-fullHash#1]
Hi,
I can't get these 2 plugins to work. 

http://wojtas82.zrujnowane.pl/utf2.html#15/54.5056/18.4848/osm-bike

As you can see link updates but when I refresh website it goes back to setView position. When I move L.hash(map, allMapLayers);

to the bottom of the code, Fullhash works but UTFGrid is not....
Any ideas? Thanks a lot in advance!

Great plugin!

**Comment by VoyteckPL** [comment]
sorry please delete.

**Comment by KoGor** [comment]
Yep, it is working with [Leaflet.utfgrid plugin](https://github.com/danzel/Leaflet.utfgrid). You just may need to tune **changeDefer** option for better perfomance and syncing.

**Comment by VoyteckPL** [comment]
I already found a solution 

Here's a working code:

http://wojtas82.zrujnowane.pl/utf2.html#16/54.4950/18.4750/osm-rowerowe-piesze

Thanks!

**Comment by KoGor** [comment]
Good, you are welcome.
